<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.company.example</groupId>
    <artifactId>standalone-project-parent</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>my-connector</artifactId>
  <name>my-connector</name>
  <properties>
    <maven.compiler.release>${java.version}</maven.compiler.release>
    <java.version>17</java.version>
    <connector-definition-version>1.0.0</connector-definition-version>
    <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
    <mockito.version>5.23.0</mockito.version>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <bonita-runtime.version>12.0-SNAPSHOT</bonita-runtime.version>
    <maven-assembly-plugin.version>3.8.0</maven-assembly-plugin.version>
    <maven-surefire.version>3.5.6</maven-surefire.version>
    <assertj-core.version>3.27.7</assertj-core.version>
    <connector-impl-id>${connector-definition-id}-impl</connector-impl-id>
    <maven.build.timestamp.format>yyyy.MM.dd-hh.mm</maven.build.timestamp.format>
    <connector-main-class>com.company.bonitasoft.MyConnector</connector-main-class>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <connector-definition-id>${project.artifactId}</connector-definition-id>
    <junit.version>6.1.3</junit.version>
    <logback-classic.version>1.6.2</logback-classic.version>
    <groovy.version>4.0.32</groovy.version>
    <connector-impl-version>${project.version}</connector-impl-version>
    <gmavenplus-plugin.version>5.1.0</gmavenplus-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.bonitasoft.runtime</groupId>
        <artifactId>bonita-runtime-bom</artifactId>
        <version>${bonita-runtime.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.bonitasoft.engine</groupId>
      <artifactId>bonita-common</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj-core.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>${logback-classic.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <defaultGoal>package</defaultGoal>
    <resources>
      <resource>
        <filtering>true</filtering>
        <directory>src/main/resources-filtered</directory>
      </resource>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
    </resources>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>${gmavenplus-plugin.version}</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <scripts>
                <script>${project.basedir}/src/script/dependencies-as-var.groovy</script>
              </scripts>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy</artifactId>
            <version>${groovy.version}</version>
          </dependency>
          <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy-xml</artifactId>
            <version>${groovy.version}</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>${maven-assembly-plugin.version}</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <descriptorSourceDirectory>${project.basedir}/src/assembly</descriptorSourceDirectory>
              <appendAssemblyId>true</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
