#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
#set( $bonitaVersionParts = $bonitaVersion.split('\.') )
#set( $shortBonitaVersion = $bonitaVersionParts.get(0) +'.'+ $bonitaVersionParts.get(1) )
#set( $after713 = $bonitaVersion.matches('7.(1[3-9]|[2-9][0-9]).*') || $bonitaVersion.matches('[8-99].[0-9]+.*') )
:doctype: book
:toc: left
:toclevels: 3
:sectnums:
:icons: font
:source-highlighter: highlightjs
:idprefix:
:idseparator: -
:sectlinks:
:sectanchors:
:linkcss: false

:short-bonita-version: ${shortBonitaVersion}
:doc-url: https://documentation.bonitasoft.com/bonita/${shortBonitaVersion}
:java-version:#if( $after713 ) 11#else 1.8#end

= ${artifactId}

The project **$artifactId** is a Bonita Connector for **Bonita {short-bonita-version}** #if("sp" == true)**Enterprise** #else **Community**#end version written in `$language` language.

_**TODO**_: A brief description of your project, what it is used for and how does life get
awesome when someone starts to use it.

== Features

_**TODO**_: What's all the bells and whistles this project can perform?

* What's the main functionality
* You can also do another thing
* If you get really handy, you can even do this

== Getting started

_**TODO**_: A quick introduction of the minimal setup you need to get a hello world up &
running.
For more details on Bonita Connector please refer to {doc-url}/connector-archetype[documentation]

== Developing
_**TODO**_: Here's a brief introduction about what a developer must do in order to start developing
the project further:

Prerequisite:

- Java ( **jdk {java-version}** or higher)
- Maven (optional if you choosed to use https://github.com/takari/maven-wrapper[maven wrapper script] as archetype option)
- A Git client (optional but highly recommended)

=== Building

_**TODO**_: If your project needs some additional steps for the developer to build the
project after some code changes, state them here:

[source,bash]
----
git clone https://your.github.com/${artifactId}.git
cd $artifactId/
#if($wrapper=="true")
./mwnw package
#else
mvn package
#end 
----

#if( $after713 )
The build should produce a jar archive under the `target/` folder named `${artifactId}-${version}.jar`#else
The build should produce a zip archive under the `target/` folder named `${artifactId}-${version}-all.zip`#end


_**TODO**_: Here again you should state what actually happens when the code above gets
executed.

For more details about Apache Maven, please refer to the https://maven.apache.org/guides/getting-started/[documentation]

=== Deploying / Publishing

_**TODO**_: In case there's some step you have to take that publishes this project to a server, this is the right time to state it.

#if( $after713 )
{doc-url}/managing-extension-studio[Install the connector in your Bonita project using the Studio, window = "_blank"].#else
Take the built artifact `${artifactId}-${version}-all.zip` and import it to your Bonita Studio.#end


== Contributing

_**TODO**_: Make easy to your team to jump in and start contributing to your project.

These paragraphs are meant to welcome those kind souls to feel that they are
needed. You should state something like:

"If you'd like to contribute, please fork the repository and use a feature
branch. Pull requests are warmly welcome."

If there's anything else the developer needs to know (e.g. the code style
guide), you should link it here. If there's a lot of things to take into
consideration, it is common to separate this section to its own file called
`CONTRIBUTING.adoc` (or similar). If so, you should say that it exists here.

== Links

_**TODO**_: Even though this information can be found inside the project on machine-readable
format like in a .json file, it's good to include a summary of most useful
links to humans using your project. You can include links like:

. Project homepage: https://your.github.com/awesome-project/
. Repository: https://github.com/your/awesome-project/
. Issue tracker: https://github.com/your/awesome-project/issues
.. In case of sensitive bugs like security vulnerabilities, please contact
    my@email.com directly instead of using issue tracker. We value your effort
    to improve the security and privacy of this project!
